package de.htw.tournament.model;
// default package
// Generated 05.02.2015 12:56:21 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Competition generated by hbm2java
 */
public class Competition implements java.io.Serializable {

	private Long identity;
	private Document document;
	private Tournament tournament;
	private short season;
	private float pointsPerWin;
	private float pointsPerDraw;
	private float pointsPerLoss;
	private Set divisions = new HashSet(0);

	public Competition() {
	}

	public Competition(Document document, Tournament tournament, short season,
			float pointsPerWin, float pointsPerDraw, float pointsPerLoss) {
		this.document = document;
		this.tournament = tournament;
		this.season = season;
		this.pointsPerWin = pointsPerWin;
		this.pointsPerDraw = pointsPerDraw;
		this.pointsPerLoss = pointsPerLoss;
	}

	public Competition(Document document, Tournament tournament, short season,
			float pointsPerWin, float pointsPerDraw, float pointsPerLoss,
			Set divisions) {
		this.document = document;
		this.tournament = tournament;
		this.season = season;
		this.pointsPerWin = pointsPerWin;
		this.pointsPerDraw = pointsPerDraw;
		this.pointsPerLoss = pointsPerLoss;
		this.divisions = divisions;
	}

	public Long getIdentity() {
		return this.identity;
	}

	public void setIdentity(Long identity) {
		this.identity = identity;
	}

	public Document getDocument() {
		return this.document;
	}

	public void setDocument(Document document) {
		this.document = document;
	}

	public Tournament getTournament() {
		return this.tournament;
	}

	public void setTournament(Tournament tournament) {
		this.tournament = tournament;
	}

	public short getSeason() {
		return this.season;
	}

	public void setSeason(short season) {
		this.season = season;
	}

	public float getPointsPerWin() {
		return this.pointsPerWin;
	}

	public void setPointsPerWin(float pointsPerWin) {
		this.pointsPerWin = pointsPerWin;
	}

	public float getPointsPerDraw() {
		return this.pointsPerDraw;
	}

	public void setPointsPerDraw(float pointsPerDraw) {
		this.pointsPerDraw = pointsPerDraw;
	}

	public float getPointsPerLoss() {
		return this.pointsPerLoss;
	}

	public void setPointsPerLoss(float pointsPerLoss) {
		this.pointsPerLoss = pointsPerLoss;
	}

	public Set getDivisions() {
		return this.divisions;
	}

	public void setDivisions(Set divisions) {
		this.divisions = divisions;
	}

}
