package de.htw.tournament.model;
// default package
// Generated 05.02.2015 12:56:21 by Hibernate Tools 4.3.1

/**
 * Competitor generated by hbm2java
 */
public class Competitor implements java.io.Serializable {

	private long competitorIdentity;
	private Document document;
	private Rankableentity rankableentity;
	private String alias;

	public Competitor() {
	}

	public Competitor(Document document, Rankableentity rankableentity,
			String alias) {
		this.document = document;
		this.rankableentity = rankableentity;
		this.alias = alias;
	}

	public long getCompetitorIdentity() {
		return this.competitorIdentity;
	}

	public void setCompetitorIdentity(long competitorIdentity) {
		this.competitorIdentity = competitorIdentity;
	}

	public Document getDocument() {
		return this.document;
	}

	public void setDocument(Document document) {
		this.document = document;
	}

	public Rankableentity getRankableentity() {
		return this.rankableentity;
	}

	public void setRankableentity(Rankableentity rankableentity) {
		this.rankableentity = rankableentity;
	}

	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

}
