package de.htw.tournament.model;
// default package
// Generated 09.02.2015 16:09:37 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Division generated by hbm2java
 */
@Entity
@Table(name = "division", catalog = "tournament", uniqueConstraints = @UniqueConstraint(columnNames = {
		"competitionReference", "alias" }))
public class Division extends Rankableentity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "rankableentity"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "divisionIdentity", unique = true, nullable = false)
	private long divisionIdentity;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "competitionReference", nullable = false)
	private Competition competition;
	
	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	private Rankableentity rankableentity;
	
	@Column(name = "alias", nullable = false, length = 1)
	private char alias;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "division")
	private Set<Game> games = new HashSet<Game>(0);

	public Division() {
	}

	public Division(Competition competition, Rankableentity rankableentity,
			char alias) {
		this.competition = competition;
		this.rankableentity = rankableentity;
		this.alias = alias;
	}

	public Division(Competition competition, Rankableentity rankableentity,
			char alias, Set<Game> games) {
		this.competition = competition;
		this.rankableentity = rankableentity;
		this.alias = alias;
		this.games = games;
	}

	
	public long getDivisionIdentity() {
		return this.divisionIdentity;
	}

	public void setDivisionIdentity(long divisionIdentity) {
		this.divisionIdentity = divisionIdentity;
	}

	
	public Competition getCompetition() {
		return this.competition;
	}

	public void setCompetition(Competition competition) {
		this.competition = competition;
	}

	
	public Rankableentity getRankableentity() {
		return this.rankableentity;
	}

	public void setRankableentity(Rankableentity rankableentity) {
		this.rankableentity = rankableentity;
	}

	
	public char getAlias() {
		return this.alias;
	}

	public void setAlias(char alias) {
		this.alias = alias;
	}

	
	public Set<Game> getGames() {
		return this.games;
	}

	public void setGames(Set<Game> games) {
		this.games = games;
	}

	@Override
	public ScoreSheetEntry getScoreSheet() {
		// TODO Auto-generated method stub
		return null;
	}

}
