package de.htw.tournament.model;
// default package
// Generated 05.02.2015 12:56:21 by Hibernate Tools 4.3.1

/**
 * Divisionscoresheetentry generated by hbm2java
 */
public class Divisionscoresheetentry implements java.io.Serializable {

	private DivisionscoresheetentryId id;

	public Divisionscoresheetentry() {
	}

	public Divisionscoresheetentry(DivisionscoresheetentryId id) {
		this.id = id;
	}

	public DivisionscoresheetentryId getId() {
		return this.id;
	}

	public void setId(DivisionscoresheetentryId id) {
		this.id = id;
	}

}
