package de.htw.tournament.model;
// default package
// Generated 05.02.2015 12:56:21 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Division generated by hbm2java
 */
public class Division implements java.io.Serializable {

	private long divisionIdentity;
	private Competition competition;
	private Rankableentity rankableentity;
	private char alias;
	private Set games = new HashSet(0);

	public Division() {
	}

	public Division(Competition competition, Rankableentity rankableentity,
			char alias) {
		this.competition = competition;
		this.rankableentity = rankableentity;
		this.alias = alias;
	}

	public Division(Competition competition, Rankableentity rankableentity,
			char alias, Set games) {
		this.competition = competition;
		this.rankableentity = rankableentity;
		this.alias = alias;
		this.games = games;
	}

	public long getDivisionIdentity() {
		return this.divisionIdentity;
	}

	public void setDivisionIdentity(long divisionIdentity) {
		this.divisionIdentity = divisionIdentity;
	}

	public Competition getCompetition() {
		return this.competition;
	}

	public void setCompetition(Competition competition) {
		this.competition = competition;
	}

	public Rankableentity getRankableentity() {
		return this.rankableentity;
	}

	public void setRankableentity(Rankableentity rankableentity) {
		this.rankableentity = rankableentity;
	}

	public char getAlias() {
		return this.alias;
	}

	public void setAlias(char alias) {
		this.alias = alias;
	}

	public Set getGames() {
		return this.games;
	}

	public void setGames(Set games) {
		this.games = games;
	}

}
