package de.htw.tournament.model;
// default package
// Generated 05.02.2015 12:56:21 by Hibernate Tools 4.3.1

/**
 * Game generated by hbm2java
 */
public class Game implements java.io.Serializable {

	private long gameIdentity;
	private Division division;
	private Rankableentity rankableentityByRightRankableEntityReference;
	private Rankableentity rankableentityByLeftRankableEntityReference;
	private Rankableentity rankableentityByIdentity;
	private byte leftOrdinal;
	private Short leftScore;
	private byte rightOrdinal;
	private Short rightScore;

	public Game() {
	}

	public Game(Rankableentity rankableentityByRightRankableEntityReference,
			Rankableentity rankableentityByLeftRankableEntityReference,
			Rankableentity rankableentityByIdentity, byte leftOrdinal,
			byte rightOrdinal) {
		this.rankableentityByRightRankableEntityReference = rankableentityByRightRankableEntityReference;
		this.rankableentityByLeftRankableEntityReference = rankableentityByLeftRankableEntityReference;
		this.rankableentityByIdentity = rankableentityByIdentity;
		this.leftOrdinal = leftOrdinal;
		this.rightOrdinal = rightOrdinal;
	}

	public Game(Division division,
			Rankableentity rankableentityByRightRankableEntityReference,
			Rankableentity rankableentityByLeftRankableEntityReference,
			Rankableentity rankableentityByIdentity, byte leftOrdinal,
			Short leftScore, byte rightOrdinal, Short rightScore) {
		this.division = division;
		this.rankableentityByRightRankableEntityReference = rankableentityByRightRankableEntityReference;
		this.rankableentityByLeftRankableEntityReference = rankableentityByLeftRankableEntityReference;
		this.rankableentityByIdentity = rankableentityByIdentity;
		this.leftOrdinal = leftOrdinal;
		this.leftScore = leftScore;
		this.rightOrdinal = rightOrdinal;
		this.rightScore = rightScore;
	}

	public long getGameIdentity() {
		return this.gameIdentity;
	}

	public void setGameIdentity(long gameIdentity) {
		this.gameIdentity = gameIdentity;
	}

	public Division getDivision() {
		return this.division;
	}

	public void setDivision(Division division) {
		this.division = division;
	}

	public Rankableentity getRankableentityByRightRankableEntityReference() {
		return this.rankableentityByRightRankableEntityReference;
	}

	public void setRankableentityByRightRankableEntityReference(
			Rankableentity rankableentityByRightRankableEntityReference) {
		this.rankableentityByRightRankableEntityReference = rankableentityByRightRankableEntityReference;
	}

	public Rankableentity getRankableentityByLeftRankableEntityReference() {
		return this.rankableentityByLeftRankableEntityReference;
	}

	public void setRankableentityByLeftRankableEntityReference(
			Rankableentity rankableentityByLeftRankableEntityReference) {
		this.rankableentityByLeftRankableEntityReference = rankableentityByLeftRankableEntityReference;
	}

	public Rankableentity getRankableentityByIdentity() {
		return this.rankableentityByIdentity;
	}

	public void setRankableentityByIdentity(
			Rankableentity rankableentityByIdentity) {
		this.rankableentityByIdentity = rankableentityByIdentity;
	}

	public byte getLeftOrdinal() {
		return this.leftOrdinal;
	}

	public void setLeftOrdinal(byte leftOrdinal) {
		this.leftOrdinal = leftOrdinal;
	}

	public Short getLeftScore() {
		return this.leftScore;
	}

	public void setLeftScore(Short leftScore) {
		this.leftScore = leftScore;
	}

	public byte getRightOrdinal() {
		return this.rightOrdinal;
	}

	public void setRightOrdinal(byte rightOrdinal) {
		this.rightOrdinal = rightOrdinal;
	}

	public Short getRightScore() {
		return this.rightScore;
	}

	public void setRightScore(Short rightScore) {
		this.rightScore = rightScore;
	}

}
