package de.htw.tournament.model;
// default package
// Generated 05.02.2015 12:56:21 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Rankableentity generated by hbm2java
 */
public class Rankableentity implements java.io.Serializable {

	private Long identity;
	private String discriminator;
	private Set gamesForRightRankableEntityReference = new HashSet(0);
	private Division division;
	private Set gamesForLeftRankableEntityReference = new HashSet(0);
	private Competitor competitor;
	private Game gameByIdentity;

	public Rankableentity() {
	}

	public Rankableentity(String discriminator) {
		this.discriminator = discriminator;
	}

	public Rankableentity(String discriminator,
			Set gamesForRightRankableEntityReference, Division division,
			Set gamesForLeftRankableEntityReference, Competitor competitor,
			Game gameByIdentity) {
		this.discriminator = discriminator;
		this.gamesForRightRankableEntityReference = gamesForRightRankableEntityReference;
		this.division = division;
		this.gamesForLeftRankableEntityReference = gamesForLeftRankableEntityReference;
		this.competitor = competitor;
		this.gameByIdentity = gameByIdentity;
	}

	public Long getIdentity() {
		return this.identity;
	}

	public void setIdentity(Long identity) {
		this.identity = identity;
	}

	public String getDiscriminator() {
		return this.discriminator;
	}

	public void setDiscriminator(String discriminator) {
		this.discriminator = discriminator;
	}

	public Set getGamesForRightRankableEntityReference() {
		return this.gamesForRightRankableEntityReference;
	}

	public void setGamesForRightRankableEntityReference(
			Set gamesForRightRankableEntityReference) {
		this.gamesForRightRankableEntityReference = gamesForRightRankableEntityReference;
	}

	public Division getDivision() {
		return this.division;
	}

	public void setDivision(Division division) {
		this.division = division;
	}

	public Set getGamesForLeftRankableEntityReference() {
		return this.gamesForLeftRankableEntityReference;
	}

	public void setGamesForLeftRankableEntityReference(
			Set gamesForLeftRankableEntityReference) {
		this.gamesForLeftRankableEntityReference = gamesForLeftRankableEntityReference;
	}

	public Competitor getCompetitor() {
		return this.competitor;
	}

	public void setCompetitor(Competitor competitor) {
		this.competitor = competitor;
	}

	public Game getGameByIdentity() {
		return this.gameByIdentity;
	}

	public void setGameByIdentity(Game gameByIdentity) {
		this.gameByIdentity = gameByIdentity;
	}

}
