package de.htw.tournament.model;
// default package
// Generated 05.02.2015 12:56:21 by Hibernate Tools 4.3.1

/**
 * Ticket generated by hbm2java
 */
public class Ticket implements java.io.Serializable {

	private Long identity;
	private byte[] valueHash;
	private Long invalidationTimestamp;

	public Ticket() {
	}

	public Ticket(byte[] valueHash) {
		this.valueHash = valueHash;
	}

	public Ticket(byte[] valueHash, Long invalidationTimestamp) {
		this.valueHash = valueHash;
		this.invalidationTimestamp = invalidationTimestamp;
	}

	public Long getIdentity() {
		return this.identity;
	}

	public void setIdentity(Long identity) {
		this.identity = identity;
	}

	public byte[] getValueHash() {
		return this.valueHash;
	}

	public void setValueHash(byte[] valueHash) {
		this.valueHash = valueHash;
	}

	public Long getInvalidationTimestamp() {
		return this.invalidationTimestamp;
	}

	public void setInvalidationTimestamp(Long invalidationTimestamp) {
		this.invalidationTimestamp = invalidationTimestamp;
	}

}
